import Head from "next/head";
import { buttonVariants } from "$/components/ui/button";
import { type NextPage } from "next";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen items-center justify-center gap-2">
        <Link href="/basic-form" className={buttonVariants()}>
          Basic Form
        </Link>

        <Link href="/password-validation" className={buttonVariants()}>
          Password Validation
        </Link>

        <Link href="/multi-step-form" className={buttonVariants()}>
          Multi Step Form
        </Link>
      </main>
    </>
  );
};

export default Home;
